---
title: "Task 4"
author: "Sophie Davies"
date: "26/11/2020"
output: html_document
---

# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, fig.retina = 3)
```

```{r packages}
library(tidyverse)
```

# Methods

```{r importing data}

file <- "data-raw/sol.txt"
sol <- read_table2(file)
names(sol)

```

```{r tidying data}

# Transpose all the values except the genename

tsol <- sol %>% 
  select(-genename) %>% 
  t() %>% 
  data.frame()

# Use the genenames in sol to name the columns in tsol:

names(tsol) <- sol$genename

# The column names of sol have become the row names of tsol. We can add a column for these as well.

tsol$sample <- row.names(tsol)

# And process the sample name so we have the cell lineage in one column and the replicate in another

tsol <- tsol %>% 
  extract(sample, 
          c("lineage","rep"),
          "(Y[0-9]{3,4})\\_([A-C])")

# Now the data should be in a format to which you can apply the methods.


```

```{r pca}


```

```{r tSNE}



```

```{r lda}
# create training and testing datasets

ids <- createDataPartition(y = tsol$lineage,
                           p = 0.75,
                           list = FALSE)

# Training set

train <- tsol %>% slice(ids)

# Testing set

test <- tsol %>% slice(-ids)

# Performing the LDA on the training data:

lda <- train %>%
  select(-c(lineage, rep)) %>%
  MASS::lda(grouping = train$lineage)

# Predict on the training data

plda_train <- train %>%
  select(-c(lineage, rep)) %>%
  predict(object = lda)

# Examining the Confusion Matrix 

confusionMatrix(plda_train$class, factor(train$lineage))

# Predict classes of the test data

plda_test <- test %>%
  select(-c(lineage, rep)) %>%
  predict(object = lda)

confusionMatrix(plda_test$class, factor(test$lineage))

```

